#!/bin/bash

#
# IMPORTANT SECURITY NOTE:
#
# This image is containing your Github Private Key in /gocd/github.pem.
#
# DO NOT COMMIT AND PUSH THIS IMAGE TO A PUBLIC REPOSITORY!!!
#

if [ -n "$GITHUB_PRIVATE_KEY" ] && [ "$ENABLE_GITHUB_PRIVATE_REPO_SUPPORT" = "yes" ] ; then
  echo "$GITHUB_PRIVATE_KEY" > /gocd/github.pem
  chown go.go /gocd/github.pem
  chmod 0400  /gocd/github.pem
fi

# add go user to instance docker group
echo "vmdocker:x:497:go" >> /etc/group

# force generation of new keystores
rm /var/lib/go-agent/config/agent.jks 2> /dev/null

if [ -n "$GO_EA_AUTO_REGISTER_KEY" ] ; then

  GO_SERVER="$GO_EA_SERVER_URL" ; export GO_SERVER

  cat <<EOF > /var/lib/go-agent/config/autoregister.properties
agent.auto.register.key=$GO_EA_AUTO_REGISTER_KEY
agent.auto.register.environments=$GO_EA_AUTO_REGISTER_ENVIRONMENT
agent.auto.register.elasticAgent.agentId=$GO_EA_AUTO_REGISTER_ELASTIC_AGENT_ID
agent.auto.register.elasticAgent.pluginId=$GO_EA_AUTO_REGISTER_ELASTIC_PLUGIN_ID
EOF

  cat <<EOF > /var/lib/go-agent/config/guid.txt
$GO_EA_GUID
EOF

  chown go.go /var/lib/go-agent/config/autoregister.properties
  chown go.go /var/lib/go-agent/config/guid.txt
fi

/sbin/my_init
